from __future__ import annotations

import zipfile
from pathlib import Path
from typing import Mapping

from .pmid import extract_pmid_groups_from_docx, unique_pmids


def write_review_docx(source_docx: str | Path, plan_rows: list[Mapping[str, str]], out_docx: str | Path) -> None:
    try:
        from docx import Document
    except ImportError as exc:
        raise RuntimeError("python-docx is required to write review .docx files") from exc

    doc = Document(str(source_docx))
    doc.add_page_break()
    doc.add_heading("Citation Plan Appendix", level=1)
    doc.add_paragraph(
        "This appendix was generated by Biomed Ref Pipeline. It does not replace Zotero insertion; it maps manuscript locations to citation actions."
    )

    table = doc.add_table(rows=1, cols=6)
    try:
        table.style = "Table Grid"
    except KeyError:
        pass
    headers = ["Citation ID", "Location", "PMIDs", "PubMed", "Zotero", "Action"]
    for cell, header in zip(table.rows[0].cells, headers):
        cell.text = header

    for row in plan_rows:
        cells = table.add_row().cells
        values = [
            row.get("citation_id", ""),
            row.get("location", ""),
            row.get("pmids", ""),
            row.get("pubmed_status", ""),
            row.get("zotero_status", ""),
            row.get("recommended_action", ""),
        ]
        for cell, value in zip(cells, values):
            cell.text = str(value)

    doc.save(str(out_docx))


def validate_final_docx(docx_path: str | Path, expected_pmids: list[str] | None = None) -> str:
    groups = extract_pmid_groups_from_docx(docx_path)
    remaining_pmids = unique_pmids(groups)
    zotero_fields = count_zotero_fields(docx_path)
    expected = expected_pmids or []
    expected_visible = [pmid for pmid in expected if pmid in remaining_pmids]

    lines = [
        "# Final DOCX Validation",
        "",
        "This report checks visible PMID placeholders and embedded Zotero field markers. It cannot prove citation correctness by itself.",
        "",
        "## Summary",
        "",
        f"- Remaining visible PMID groups: {len(groups)}",
        f"- Remaining visible unique PMIDs: {len(remaining_pmids)}",
        f"- Embedded Zotero field markers: {zotero_fields}",
        f"- Expected PMIDs still visible: {len(expected_visible)}",
        "",
    ]

    if groups:
        lines.append("## Remaining PMID Markers")
        lines.append("")
        for group in groups:
            lines.append(f"- `{group.location}`: `{group.raw_text}`")
        lines.append("")

    if expected and expected_visible:
        lines.append("## Expected PMIDs Still Visible")
        lines.append("")
        lines.append("These may not have been replaced by Zotero citations:")
        lines.append("")
        lines.append(" ".join(expected_visible))
        lines.append("")

    if not groups and zotero_fields:
        lines.extend(["## Status", "", "- No visible PMID placeholders remain and Zotero fields were detected.", ""])
    elif not groups:
        lines.extend(["## Status", "", "- No visible PMID placeholders remain. Zotero fields were not detected by XML scan.", ""])
    else:
        lines.extend(["## Status", "", "- Visible PMID placeholders remain. Review before final submission.", ""])
    return "\n".join(lines)


def count_zotero_fields(docx_path: str | Path) -> int:
    count = 0
    with zipfile.ZipFile(docx_path) as archive:
        for name in archive.namelist():
            if not name.startswith("word/") or not name.endswith(".xml"):
                continue
            text = archive.read(name).decode("utf-8", errors="ignore")
            count += text.count("ZOTERO_ITEM CSL_CITATION")
            count += text.count("ZOTERO_BIBL")
    return count
